turtlebot3_fake_node:
  ros__parameters:

    wheels:
      separation: 0.160
      radius: 0.033

    wheel_left_joint_name: "wheel_left_joint"
    wheel_right_joint_name: "wheel_right_joint"
    joint_states_frame: "base_footprint"
    odom_frame: "odom"
    base_frame: "base_footprint"