turtlebot3_fake_node:
  ros__parameters:
    tb3_model: ""
    wheel_left_joint_name: "wheel_left_joint"
    wheel_right_joint_name: "wheel_right_joint"
    joint_states_frame: "base_footprint"
    odom_frame: "odom"
    base_frame: "base_footprint"